// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/kaixinhupo/quick/controller"
	"github.com/kaixinhupo/quick/dao/database"
	"github.com/kaixinhupo/quick/dao/repository"
	"github.com/kaixinhupo/quick/service/biz"
	"github.com/kaixinhupo/quick/service/contract"
)

import (
	_ "github.com/kaixinhupo/quick/docs"
)

// Injectors from wire.go:

func InitUserController() *controller.UserController {
	userRepositoryImpl := database.NewUserRepository()
	userServiceImpl := biz.NewUserService(userRepositoryImpl)
	userController := controller.NewUserController(userServiceImpl)
	return userController
}

// wire.go:

var userRepositorySet = wire.NewSet(database.NewUserRepository, wire.Bind(new(repository.UserRepository), new(*database.UserRepositoryImpl)))

var userServiceSet = wire.NewSet(biz.NewUserService, wire.Bind(new(contract.UserService), new(*biz.UserServiceImpl)))
